### PR TITLE
Some typos fixes to come into the history of the contemporary cyberpunk

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by JJ** [comment]
Thanks a lot for your corrections. Was this  part of a hackaton, a class? 
I'll have to cherry-pick the changes; some of the typos (electrickal) were intentional. I'll be doing it in a minute (of maybe I'll just merge and redo afterwards :-))

**Comment by JJ** [comment]
BTW, did you like it, in general?

**Comment by yarikoptic** [comment]
Hi @JJ !  It was indeed a "bi-product" of a little git bootcamp.  Unfortunately I have not read it (yet).  If I come back, next time do not hesitate to just say what to fix in proposed changes -- I would just update the PR.  Cheers!

**Comment by hoborgist** [comment]
Great!

I guess it still needs some proof-reading so if you find any typo/grammar
awkwardness/error or just don't like the ending, feel free!

**Pull request merged**
